### ISSUE TITLE
Crear programa inserción BD

### ISSUE THREAD

**Issue by CodePicker98** [CodePicker98/proyectoLAPD#4]
Desarrollar un programa en java para leer el archivo .csv e insertar los datos en la base de datos.

**Comment by LuisValeroMolina** [comment]
Se podrá ir actualizando el .csv

**Comment by jesuseverisschool** [comment]
https://www.2ndquadrant.com/en/blog/using-java-arrays-to-insert-retrieve-update-postgresql-arrays/
