### ISSUE TITLE
HTML Área-Crimen

### ISSUE THREAD

**Issue by LuisValeroMolina** [CodePicker98/proyectoLAPD#9]
Para la funcionalidad:

Se quiere poder generar un informe en HTML en el que, a partir del área indicada por el
usuario, muestre los siguientes datos: número de delitos cometidos, cuántas víctimas
son mujeres y cuántas hombres, cuántas son blancas, negras, hispanas u otras y la
edad media de la víctimas.

**Comment by CodePicker98** [comment]
https://www.opendatanetwork.com/dataset/data.lacity.org/y8tr-7khq
